### PR TITLE
Basic (un)support via AJAX

### PR DESCRIPTION
**Pull request by aviraldg**
Fixes arguman/arguman.org#206

### CODE REVIEW

**Comment by aviraldg** [comment]
@fatiherikli This was merged and reverted, right?

**Comment by fatiherikli** [comment]
Yes, it was a mistake.

**Comment by fatiherikli** [comment]
Could you create a new pull request after the fix?

**Comment by aviraldg** [comment]
Sure! Are you open to the idea of making this a single page app with a lighter backend? That'd make features like this easier to implement.

**Pull request merged**
