### PR TITLE
Add a Polish translation

### PR DESCRIPTION
**Pull request by fizyk20**
This PR adds a translation of Arguman into Polish.

I had to remove a `pl` folder that contained strings in some other language - Portuguese, maybe? I can restore it under some other name, if necessary, but it didn't seem to be used anywhere, anyway.

If any further changes are needed to polish (pun not intended) the PR, please let me know.

### CODE REVIEW

**Comment by fatiherikli** [comment]
dzięki! :)

**Comment by fatiherikli** [comment]
deployed on https://pl.arguman.org/

**Comment by fizyk20** [comment]
Awesome, thanks! :)

I noticed, though, that Polish shows as "Polskie" in the list of languages on the live website, but it should be "Polski". I double-checked the code (`web/templates/base.html') and it's "Polski" there, even here in the main repo (although wrapped in a probably unnecessary `{% trans %}`), so I'm slightly puzzled. Any idea why that happens?

**Comment by fatiherikli** [comment]
It was my mistake, sorry! I was trying something on the production (off the record) 😶

It should be done now.

**Comment by fizyk20** [comment]
No worries! And thanks again :slightly_smiling_face:

**Comment by fatiherikli** [comment]
It could be awesome if you can send some initial arguments :) @fizyk20 

Btw, currently I am living in Poland as well. I will use this to practice my polish :)

**Comment by fizyk20** [comment]
> It could be awesome if you can send some initial arguments :)
I'll try, but TBH I don't really have ideas for arguments right now ;)

> Btw, currently I am living in Poland as well. I will use this to practice my polish :)
Haha, cool! :D

**Pull request merged**
