### PR TITLE
First step to break the monolith. Splitting into unit classes.

### PR DESCRIPTION
**Pull request by EHadoux**
This is the first step for a decoupling between business logic and web stuffs. 
Do you want me to carry on?
Feel free to modify or reject but please **do not merge yet**.

### CODE REVIEW

**Comment by EHadoux** [comment]
I insist, **do not** merge. It does not work at the moment but I pull-requested for you to see the direction.
I'll tell you when I judge it testable.

**Comment by fatiherikli** [comment]
Separating models is not a good practice in django. I think Python's modules and namespaces are already pretty good. So this is not an enhancement to separation of concerns.

**Comment by EHadoux** [comment]
Thanks for the reading. So if I understand it well enough, throwing all your models in one huge file is considered good practice in Django?
Moreover, not everybody considers it as a good practice: [here](http://stackoverflow.com/a/1160735) or [there page 28](https://books.google.fr/books?id=WzW9BwAAQBAJ&lpg=PA28&ots=mh5R04N0nW&dq=django%20model%20good%20practice%20models.py&hl=fr&pg=PA29#v=onepage&q=django%20model%20good%20practice%20models.py&f=false)

As for arguman.org repository, I think it is good. But I also think it could be better to have a blog repo, a newsfeed repo, a argument map repo, all include in the arguman.org repo for those wanting the whole stuff but letting others picking what it is useful for them if they just want, say, the map and the api.

**Comment by fatiherikli** [comment]
One huge file? Actually premise.models have just 3 models, and separating these models will not gain anything about separation of concerns.

**Comment by EHadoux** [comment]
I am sorry if I seemed aggressive, that was not intended.
However, the file actually contains 5 classes and has more than 400 LOC.
I totally agree with you that splitting up will not reduce the number of LOC though, quite the opposite in fact. But it the first step to separate all.
In the current situation, if, for instance, I want to only use your hierarchy of classes with a visual presentation of my own, I still have to deal with the DB part, the blog, etc.

**Pull request closed without merging**
