### PR TITLE
Spanish translation draft

### PR DESCRIPTION
**Pull request by jorgebg**
First draft, there are only a couple of messages

### CODE REVIEW

**Comment by jorgebg** [comment]
I would maintain it in a different branch as in my fork (`locale-es`) until it is completed.

**Comment by fatiherikli** [comment]
Looks good :') Can you also translate about-en.md after this is completed?

**Comment by jorgebg** [comment]
@fatiherikli of course I'll translate it too :smile:

**Comment by fatiherikli** [comment]
Will you translate example arguments? It need not be same, you can write any other example arguments in your language.

https://github.com/jorgebg/arguman.org/blob/29812b3e36c33751a24e376d5e400b839a228631/web/locale/es/LC_MESSAGES/django.po#L694

**Comment by jorgebg** [comment]
@fatiherikli ok I take note of it!

**Comment by jorgebg** [comment]
It passed more than a year but you keept this PR open :) great news, @alejoduque finished the translations! The version is from November 2016, but I think it is ok for the first version, what do you think @fatiherikli?

**Comment by alejoduque** [comment]
Yes, some little minor things to comment and translate. But it will be great to test it (I haven't been able to successfully install it on my debian server and will appreciate any help, please let me know where will it be best to report my issues).

**Comment by alejoduque** [comment]
Thank you also Jorge for starting the job!

**Comment by jorgebg** [comment]
Thank you @alejoduque , I'm sorry I couldn't finish it!

**Pull request closed without merging**
